name: Ronald Cray
favicon: null
layout_spectrum: 0.05685
typography_spectrum: 0.015033336356282234
title: 'Space for him to live on '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#152131'
    - '#d56945'
    - '#784a3b'
    - '#cbba8c'
    - '#af9876'
  brandStrength: 0.625
  lightness: 0.5764761895406991
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
