name: Ronald Cray
favicon: null
layout_spectrum: 0.75185
typography_spectrum: 0.85068
title: Ronald Cray
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a7bac0'
    - '#2e2f2a'
    - '#b78b34'
    - '#565a4b'
    - '#872a22'
  brandStrength: 0.5
  lightness: 0.5764761895406991
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
