typography_spectrum: 0.85068
color:
  brandColors:
    - '#a7bac0'
    - '#2e2f2a'
    - '#b78b34'
    - '#565a4b'
    - '#872a22'
  brandStrength: 0.5
  lightness: 0.5764761895406991
  saturation: 0.875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75185
analytics:
  google: null
  facebook: null
  twitter: null
name: Ronald Cray
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ronald Cray
description: in rememberence
purpose: []
